name: bondquest_2d
description: Lightweight downloadable 2D couple and family game.
version: 0.2.0+2
publish_to: none
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
